genome: "hg19"
hg19_bowtie2_index: "/2.genome/bowti2_index/hg19/hg19"
hg19_blacklist: "/hg19_blacklist/hg19_atac_consensusBlacklist.bed"
hg19_sizes: "/hg19.sizes"
mm10_blacklist: "/mm10_blacklist/mm10.blacklist.bed"
mm10_sizes: "/genomes/sizes/mouse.mm10.genome.sizes"
picard_markdup: "/picard_1.122/MarkDuplicates.jar"
