index: "/bwa_index/hg19/hg19"
tempdir: "/home/rcf-40/amalthom/staging_work"
chrom_file: "/genome/coordinates/hg19.sizes"
ref_seq: "/genomes/human/hg19/hg19.fasta"
exome_list: "/genomes/gatk_resources/hg19_exome.bed"
gatk_jar: "/exome/GenomeAnalysisTK.jar"
