---
title: "heatmap for mice microenvironment"
output: html_notebook
author: "A.Thomas"
---

```{r}
suppressPackageStartupMessages({
library(RColorBrewer)
library(ggplot2)
library(gplots)
library(data.table)
})
source("data/heatmap.3.R")
```

read mm10ensembl gene ids
```{r, echo=FALSE}
mm10_file="data/mm10_gene_details.tsv"
symbols = read.table(mm10_file,sep="\t",quote = "",row.names = NULL)
colnames(symbols) <- c("ensembl_gene_id", "gene_symbol")
```

read design matrix

```{r}
design.matrix = read.table("data/RNAseq_menv_design_matrix.tsv",
                           sep = "\t",row.names = 1,header = T)
#only require brain samples
design.matrix = design.matrix[design.matrix$tissue=="brai",]
design.matrix$tissue = factor(design.matrix$tissue)
design.matrix$cellline = factor(design.matrix$cellline)
design.matrix
```
read RLD transformed counts table
```{r}
path="data/"
df = read.table(paste0(path,"RNAseq_menv_counts_RLDtransformed.tsv"),
                sep="\t",header = T,row.names = 1)
outputname="menv"
df = df[,rownames(design.matrix)]
df[1:5,1:3]
```
load the DE genes
```{r}
de.up = read.table("data/RNAseq_menv_brainmenv-vs-braincontrols_up_fdr0.05.tsv",
                   sep="\t",header = T)
de.down = 
  read.table("data/RNAseq_menv_brainmenv-vs-braincontrols_down_fdr0.05.tsv",
             sep = "\t",header = T)
de_genes = unique(c(as.vector(de.up$ensembl_gene_id),
                    as.vector(de.down$ensembl_gene_id)))
length(de_genes)
```

```{r}
df1 = df[de_genes,]
df1$ensembl_gene_id = rownames(df1)
df1 = merge(df1,symbols,by="ensembl_gene_id",sort=FALSE)
dim(df1)
setDT(df1)[gene_symbol==" ",gene_symbol:=ensembl_gene_id]
df1$gene_name = NULL
df1$ensembl_gene_id = NULL
df1 = as.data.frame(df1)
df1 = df1[,c(ncol(df1),1:(ncol(df1)-1))]
head(df1[,1:3])
#write.table(df1,file="DE_datafile.tsv",sep="\t",quote = F,row.names = F)
rownames(df1) = df1$gene_symbol
df1$gene_symbol = NULL
```

heatmap with sorting columns
```{r}
mat = df1
colnames(mat) = gsub("X","",colnames(mat))
mypalette <- brewer.pal(11,"RdYlBu")
morecolors <- colorRampPalette(mypalette)
row.cell = c(rep("#4DAF4A",181),rep("#984EA3",37))
col.cell = c("#E41A1C","#377EB8")[design.matrix$cellline]
pdf(file=paste0(outputname,"_colsort.pdf"))
heatmap.2(as.matrix(mat),col=rev(morecolors(50)),trace="none",keysize=1,
          density.info="none",ColSideColors=col.cell,RowSideColors=row.cell,
          scale="row",Colv = T,Rowv = F,dendrogram = "column")
legend("topright",legend=c("50menv","50control","DE up","DE down"),
       fill=c("#E41A1C","#377EB8","#4DAF4A","#984EA3"), border=FALSE, bty="n",
       y.intersp = 0.7, cex=0.7)
dev.off()
```
